export const reducerCases = {
    SET_TOKEN : "SET_TOKEN",
    SET_USER:"SET_USER",
    SET_USER_PLAYLISTS:"SET_USER_PLAYLISTS",
    SET_CURRENT_PLAYLIST : "SET__CURRENT_PLAYLIST",
    SET_PLAYING:"SET_PLAYING",
    SET_EDIT_POP_UP: "SET_EDIT_POP_UP",
    SET_SCROLL : "SET_SCROLL",
    SET_CURRENT_SONG : "SET_CURRENT_SONG",
    SET_PREVIOUS_SONG : 'SET_PREVIOUS_SONG',
    SET_VOLUME : "SET_VOLUME"
}

export const root = 'http://localhost:3000';