export const reducerCases = {
    SET_TOKEN : "SET_TOKEN",
    SET_PLAYLISTS : "SET_PLAYLISTS",
    SET_USER:"SET_USER",
    SET_USER_PLAYLISTS:"SET_USER_PLAYLISTS",
    SET_PLAYING:"SET_PLAYING",
    SET_PLAYLIST_ID:"SET_PLAYLIST_ID",
    SET_POP_UP: "SET_POP_UP",
    SET_SCROLL : "SET_SCROLL",
    SET_CURRENT_SONG : "SET_CURRENT_SONG",
    SET_PREVIOUS_SONG : 'SET_PREVIOUS_SONG',
    SET_VOLUME : "SET_VOLUME"

}